# Generated by Django 4.0.4 on 2022-05-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Tracker_App', '0002_alter_attendanceuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
