# Generated by Django 4.0.4 on 2022-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Tracker_App', '0004_alter_attendanceuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregister',
            name='entryTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='exitTime',
            field=models.TimeField(null=True),
        ),
    ]
