# Generated by Django 4.0.4 on 2022-05-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Tracker_App', '0005_alter_attendanceregister_entrytime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceregister',
            old_name='user',
            new_name='attuser',
        ),
    ]
