# Generated by Django 4.0.4 on 2022-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Tracker_App', '0006_rename_user_attendanceregister_attuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceregister',
            name='attuser',
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='regno',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
