# Generated by Django 4.0.4 on 2022-05-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Tracker_App', '0008_attendanceregister_attendance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceregister',
            old_name='entry_lateorearly',
            new_name='entryLateorEarly',
        ),
        migrations.RenameField(
            model_name='attendanceregister',
            old_name='exit_lateorearly',
            new_name='exitLateorEarly',
        ),
    ]
